Repository keironchaudhry/june-pride-hackathon-2023, pull requests merged in 2023-06, with the labels that each got.

#1 Keiron: Setup project + create instructions for PR and branches
  README.md
  assets/css/style.css
  assets/documentation/readme_images/2 branches.png
  assets/documentation/readme_images/bad branch.png
  assets/documentation/readme_images/branch-ide.png
  assets/documentation/readme_images/good branch.png
  assets/documentation/readme_images/new pr button.png
  assets/documentation/readme_images/source_control.png
  assets/documentation/readme_images/sync_changes.png
  assets/documentation/readme_images/three_dots.png
  assets/documentation/readme_images/unmissable-message.png
  assets/js/script.js
  index.html
Labels: good first issue

#2 Documentation: Create issue templates
  .github/ISSUE_TEMPLATE/tasks-template.md
  .github/ISSUE_TEMPLATE/user-story-template.md
Labels: documentation

#3 Add podcast images
  assets/images/Pod-Elijah.jpg
  assets/images/Pod-Emily.jpg
  assets/images/Pod-Mark.jpg
  assets/images/Pod-Nikki.jpg
  assets/images/Pod-Pedro.jpg
Labels: documentation

#8 empathetic questions and discussion.html
  assets/js/script.js
  discussion.html
Labels: frontend

#9 Fix: Reformat JS file
  assets/js/script.js
Labels: bug, frontend

#10 Sam petchey: Fix speech marks
  assets/js/script.js
Labels: frontend

#11 add 36 empathetic question strings to the js const
  assets/js/script.js
Labels: documentation

#13 Feat: Add CDN for css/js for materialize across html files
  assetlist.html
  discussion.html
  index.html
  testimonials.html
Labels: enhancement, frontend

#18 Feat: Create navigation bar
  assets/css/style.css
  history.html
Labels: frontend

#19 Add Mark transparent png image
  assets/images/Pod-Mark_transp.png
Labels: documentation

#20 Samuel dev
  .vscode/settings.json
  assets/css/style.css
  index.html
Labels: enhancement, frontend

#23 Add 3 visuals for landing page and favicon/Plus symbol for logo
  assets/images/Landing-page-visual-P1.jpg
  assets/images/Landing-page-visual-P2.jpg
  assets/images/Landing-page-visual-P3.jpg
  assets/images/Plus-Symbol.png
Labels: documentation

#25 Keiron: Development of History page
  assets/css/style.css
  assets/images/hero-image-history.png
  assets/images/marsha-johnson.jpg
  history.html
Labels: frontend

#26 Samuel dev
  assets/css/style.css
  assets/images/Business-Women-front.png
  assets/images/Standing-Women.png
  assets/images/Women-Exercising.png
  home.html
  index.html
Labels: frontend

#27 Add asset list to home page
  assetlist.html
  home.html
  index.html
  testimonials.html
Labels: enhancement, frontend

#29 Keiron: Update to historical figures page
  assets/images/alanturing.jpg
  assets/images/ellen-degeneres.jpg
  assets/images/rupaul.jpg
  history.html
Labels: enhancement, frontend

#28 Remove assetlist html and place content into home
  assetlist.html
  assets/js/testimonials.js
  home.html
Labels: enhancement, frontend

#31 Sam petchey
  Pod-Emily.jpg
  assets/css/style.css
  assets/images/conversation1.png
  assets/images/conversation2.jpg
  assets/images/conversation3.png
  assets/js/script.js
  discussion.html
Labels: frontend

#30 Updated Footer
  index.html
Labels: frontend

#32 Keiron: Fix index.html post-merge
  assets/css/style.css
  assets/images/event.jpg
  history.html
  index.html
Labels: bug

#33 Change styling for audio
  assets/css/style.css
  assets/js/testimonials.js
  home.html
Labels: enhancement, frontend

#34 Sam petchey
  assets/css/style.css
  discussion.html
Labels: frontend

#35 Replace 3 landing page images
  assets/images/Landing-page-visual-P1.jpg
  assets/images/Landing-page-visual-P2.jpg
  assets/images/Landing-page-visual-P3.jpg
Labels: documentation

#36 Samuel dev
  assets/css/style.css
  assets/images/Pod-Emily.jpg
  assets/images/favicon.ico
  conversation.html
  discussion.html
  history.html
  index.html
  milestones.html
  testimonials.html
Labels: frontend

#37 Keiron: Update and fix branch
  assets/css/style.css
  milestones.html
Labels: bug, frontend

#39 Improve Conversation and Testimonials page
  assets/js/script.js
Labels: enhancement

#40 Samuel dev
  assets/css/style.css
  milestones.html
  testimonials.html
Labels: frontend

#41 Keiron: Implementation of README.md structure + Milestones page content completion
  .vscode/settings.json
  README.md
  assets/images/aids-crisis.jpg
  assets/images/decrim-homosexuality.jpg
  assets/images/marriage-equity.jpg
  assets/images/stonewall.jpg
  milestones.html
Labels: documentation, frontend

#42 Fixed links on testimonial navbar.
  milestones.html
Labels: frontend

#43 Update on Testimonials page
  conversation.html
  testimonials.html
Labels: enhancement

#44 Add css style update
  assets/css/style.css
Labels: enhancement

#46 Samuel dev
  assets/css/style.css
  milestones.html
  testimonials.html
Labels: frontend

#48 Keiron: Updates to README.md file
  README.md
  assets/documentation/readme_images/amiresponsive.png
Labels: documentation

#47 Update color scheme of testimonials page
  assets/css/style.css
  testimonials.html
Labels: enhancement

#49 Fix: Adjust file path for images
  assets/css/style.css
Labels: bug

#50 Readme: Manual testing
  README.md
Labels: documentation

#51 Samuel dev
  assets/css/style.css
  conversation.html
  index.html
  milestones.html
  testimonials.html
Labels: frontend

#54 Add hamburger menu for smaller screens
  assets/css/style.css
  assets/js/testimonials.js
  conversation.html
  milestones.html
  testimonials.html
Labels: enhancement, frontend

#55 Fix: Rebase my branch
  404.html
  index.html
  milestones.html
Labels: bug, frontend

#53 Replace second here image with exact measures
  assets/images/hero-image-history.png
Labels: enhancement

#56 Add second hero image after tinypng
  assets/images/hero-image-history.png
Labels: enhancement

#57 Read: Update amiresponsive image
  assets/documentation/readme_images/amiresponsive.png
Labels: documentation

#58 Samuel dev
  404.html
  assets/css/style.css
  conversation.html
  index.html
  milestones.html
  testimonials.html
Labels: bug, frontend

#59 Keiron: Complete revamp of milestones.html page
  assets/css/style.css
  assets/images/aids-crisis.jpg
  assets/images/alanturing.jpg
  assets/images/decrim-homosexuality.jpg
  assets/images/ellen-degeneres.jpg
  assets/images/ellendegeneres.jpg
  assets/images/marriage-equity.jpg
  assets/images/marsha-johnson.jpg
  assets/images/marshajohnson.jpg
  assets/images/rupaul.jpg
  assets/images/stonewall.jpg
  assets/images/stonewallremembrance.jpg
  milestones.html
Labels: enhancement, frontend

#60 Add design content to README file + Add wireframe visuals
  assets/documentation/readme_images/color-palette.png
  assets/documentation/readme_images/conversation.png
  assets/documentation/readme_images/index.png
  assets/documentation/readme_images/milestones.png
  assets/documentation/readme_images/testimonials.png
Labels: documentation

#61 Keiron: Validation testing in README.md
  README.md
  assets/documentation/readme_images/2 branches.png
  assets/documentation/readme_images/bad branch.png
  assets/documentation/readme_images/branch-ide.png
  assets/documentation/readme_images/css-validator.png
  assets/documentation/readme_images/good branch.png
  assets/documentation/readme_images/html-validator.png
  assets/documentation/readme_images/new pr button.png
  assets/documentation/readme_images/source_control.png
  assets/documentation/readme_images/sync_changes.png
  assets/documentation/readme_images/three_dots.png
  assets/documentation/readme_images/unmissable-message.png
  assets/js/script.js
  assets/js/testimonials.js
Labels: documentation, frontend

#62 Add mobile side bar to all pages
  404.html
  README.md
  assets/css/style.css
  conversation.html
  index.html
  milestones.html
  testimonials.html
Labels: enhancement

#63 Keiron: Features section of README.md
  README.md
  assets/documentation/features/conversation-page.png
  assets/documentation/features/footer.png
  assets/documentation/features/landing-page.png
  assets/documentation/features/milestones-page-example-event.png
  assets/documentation/features/milestones-page-example.png
  assets/documentation/features/milestones-page-second-hero.png
  assets/documentation/features/milestones-page.png
  assets/documentation/features/testimonials-page-example.png
  assets/documentation/features/testimonials-page.png
Labels: documentation

#64 Keiron: Final touches to readme
  README.md
Labels: documentation

#65 FInalised README file + Margin fix for 404 error page
  404.html
  README.md
  assets/css/style.css
  conversation.html
  milestones.html
  testimonials.html
Labels: enhancement, frontend

#67 Samuel dev
  assets/css/style.css
  milestones.html
Labels: frontend

#66 Add ALT and ARIA-LABEL to all pages
  404.html
  README.md
  conversation.html
  index.html
  testimonials.html
Labels: enhancement

#68 Samuel dev
  assets/css/style.css
  robots.txt
  sitemap.xml
Labels: bug, documentation

#69 Fixed sidenav not oppening on conversation page.
  conversation.html
Labels: bug
